### ISSUE TITLE
Mac下默认安装后无法正常使用

### ISSUE THREAD

**Issue by zhouji** [justan/twei#11]
MacOSX 10.8:
twei --version
env: node\r: No such file or directory

用dos2unix工具将twei_cli.js转成unix格式后正常。
请将twei_cli.js的换行符转换成unix的格式。

**Comment by justan** [comment]
都是 `core.autocrlf = ture` 害的. 代码库中的格式是 unix 的, 但是 npm 发布的时候却是 dos 的.
新发布了 v0.2.6 版本修正此问题.
