### ISSUE TITLE
参数自动补全

### ISSUE THREAD

**Issue by justan** [justan/twei#2]
命令行工具怎能没有参数补全?
*nix 下应该没有问题. windows 似乎没有有效的解决方案( powershell? ).

**Comment by justan** [comment]
用 [tabtab](https://github.com/mklabs/node-tabtab) 实现了 bash 和 zsh 下的自动补全. 使用 twei 的自动补全必须手动启用: `twei completion >> ~/.bashrc`.

**Comment by linhuiw** [comment]
为什么要用tabtab啊？还要手动启用。
直接用readline.createInterface(options)里的completer function ，来写这些自动不全，就不用手动开启，岂不是更好。
link:http://nodejs.org/api/readline.html#readline_rl_write_data_key

**Comment by justan** [comment]
@snipwu 你确定用 readline 可以用在 bash 的命令行做参数自动补全? 请给个例子吧.
手动启用是沿用 [npm 的惯例](https://npmjs.org/doc/completion.html). 关于为什么, isaacs 有过[说明](https://github.com/hij1nx/complete/issues/6#issuecomment-5815574)

**Comment by linhuiw** [comment]
redline是可以在bash下做参数自动补全的。官方的DEMO就可以用。
我这里做了一个gist，你可以试试看。https://gist.github.com/3404203

**Comment by justan** [comment]
@snipwu 觉得我们说的不是同一种情景. readline 的 completer 是需要 node 程序在运行中才会起作用, 就是需要提前运行: `node redline-complete.js`. 而 twei 使用的 tabtab 参数补全, 是不需要提前运行 twei 的.

**Comment by linhuiw** [comment]
@justan 明白了，感谢。
抱歉，提了一个这么啥的问题。

**Comment by justan** [comment]
@snipwu 欢迎交流 :)
